### ISSUE TITLE
Config changes to disable adding staterror systematics?

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/cabinetry#276]
It would be great to have a way to have the cabinetry example build a workspace similar to the `pyhf.simplemodels` from ntuples without having to change it too much (e.g. to use `lumi` or strip `staterror`).

**Comment by alexander-held** [comment]
Thanks for this suggestion! A staterror configuration option is a useful and straightforward addition.

I am curious about the use of `lumi`, is there a reason to prefer it over a `normsys` modifier (which in my experience is more useful for combinations)? We could think about also adding a configuration for that. Related: https://github.com/scikit-hep/pyhf/issues/1516.

**Comment by kratsg** [comment]
> I am curious about the use of `lumi`, is there a reason to prefer it over a `normsys` modifier (which in my experience is more useful for combinations)?

It's just an example. Although not clear from when I quickly filed the issue.

Thinking more about this, we probably should allow the user to have some control over how the workspace is built, or at least maybe ensure that systematics they don't explicitly define don't show up -- because this might cause confusion down the line if they don't inspect the resulting workspace that closely.

**Comment by alexander-held** [comment]
The `staterror` modifiers get added to the workspace automatically as the relevant information is available and the modifiers are usually needed. The advantage of this is that they cannot accidentally be forgotten to be included. I see the argument of possible confusion regarding the origin of these modifiers, and indeed the scenario where users explicitly do not want them included but would have to manually prune a workspace after creation. This needs to be configurable, and I would lean towards turning these modifiers on by default, but happy to hear other opinions.

> determine how much control to give the users at the level of the library

I think more (and possibly optional) control is generally better here. Do you have examples beyond `staterror` and `lumi` in mind for this?

**Comment by alexander-held** [comment]
Another important related addition is the option to remove `staterror` per sample, e.g. to exclude signal samples.

**Comment by alexander-held** [comment]
#359 adds a per-sample option to disable the automatic creation of `staterror` modifiers. This is only per-sample at the moment, with no global flag to turn it off completely.

A global option could be added easily as well, with the possibility to override it on a per-sample level. That could for example be used to turn the modifiers off for every sample, and then manually turn them on again for a single sample (instead of having to alternatively disable them for all the remaining samples one by one).

For now I am leaning towards not adding a global config option to the `General` block to keep the option structure streamlined. Users then would not have to understand how global options interact with per-sample options (though the method would be in line with a few other settings in `cabinetry`). I am happy to consider other solutions here though.
