### ISSUE TITLE
Ranking plot parameter order: max impact rather than average impact?

### ISSUE THREAD

**Issue by lhenkelm** [scikit-hep/cabinetry#372]
The ordering of parameters in `cabinetry.visualize.ranking` [sorts parameters by the _average_ post-fit up- and down- impact](https://github.com/scikit-hep/cabinetry/blob/master/src/cabinetry/visualize/__init__.py#L529).
IMO a more natural/useful ordering is _greatest_ post-fit impact in whichever direction 
(i.e. `np.maximum(np.abs(postfit_up), np.abs(postfit_down))`), 
since unlike the average,  this corresponds to a potential fit behavior (pulling the parameter significantly in a given direction).
Ofc. for many cases there should be basically no difference.
But in the cases where it does make a difference (parameters with very asymmetric/one-sided impact)
these "weird" parameters are sorted lower by the average impact & could even be hidden when also using `max_parameters`.

OTOH I noticed that `cabinetry.visualize.plot_result.ranking` [already uses the max](https://github.com/scikit-hep/cabinetry/blob/628150152c8bc309a2ffb88b2f3ac95582bcbb74/src/cabinetry/visualize/plot_result.py#L225) for axis limits, so is there maybe a reason to use the avg. when sorting?

**Comment by alexander-held** [comment]
Hi @lhenkelm, I agree that an ordering by the maximum impact in either direction makes more sense here for the reasons you mention. The max is used for the visualization range just to ensure nothing exceeds the axis range.

Feel free to submit a PR changing the ordering if you'd like, otherwise I can also take care of it.
